services:
  - type: web
    name: gaf-rtdls-nest
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      - key: JWT_EXPIRES_IN
        value: 12h
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gaf-rtdls-nest-db
          property: connectionString

databases:
  - name: gaf-rtdls-nest-db
    plan: free
